import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {runDueReminders} from '../lib/reminders';
import {cleanDeletedFiles} from '../lib/patients';
import {demoStudio} from '../lib/demo';
function setup(){const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));const wrap=(sql:string,params:any[]=[])=>({bind:(...p:any[])=>wrap(sql,p),all:async()=>({results:sqlite.prepare(sql).all(...params)}),first:async()=>sqlite.prepare(sql).get(...params)||null,run:async()=>sqlite.prepare(sql).run(...params)});return {sqlite,db:{prepare:wrap} as unknown as D1Database};}
test('reminders select only due, consenting, active patients and deduplicate executions',async()=>{const {sqlite,db}=setup(),s=demoStudio();const put=(id:string,kind:string,data:unknown)=>sqlite.prepare('INSERT INTO studio_records VALUES(?,?,?,?,?)').run(id,'owner',kind,JSON.stringify(data),'2026-10-09');for(let n=0;n<6;n++){put('p'+n,'patients',{...s.patients[0],id:'p'+n,email:'test'+n+'@example.org',archived:n===1,emailConsent:n!==2});put('a'+n,'appointments',{...s.appointments[0],id:'a'+n,patientId:'p'+n,date:n===3?'2026-10-15':'2026-10-10',time:'12:00',status:n===4?'Annullato':n===5?'Completato':'Confermato',reminderHours:24});}const previous=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({id:'mail-test'})};try{const env={RESEND_API_KEY:'fake',MAIL_FROM:'sender@example.org'};const result=await runDueReminders(db,env,new Date('2026-10-09T12:00:00Z'));assert.equal(result.accepted,1);assert.equal(result.skipped,5);assert.equal(calls,1);const repeated=await runDueReminders(db,env,new Date('2026-10-09T12:01:00Z'));assert.equal(repeated.accepted,0);assert.equal(calls,1);}finally{globalThis.fetch=previous;sqlite.close();}});
test('uncertain network results are recorded and not automatically resent',async()=>{const {sqlite,db}=setup(),s=demoStudio();sqlite.prepare('INSERT INTO studio_records VALUES(?,?,?,?,?)').run('p','owner','patients',JSON.stringify({...s.patients[0],id:'p',email:'test@example.org'}),'now');sqlite.prepare('INSERT INTO studio_records VALUES(?,?,?,?,?)').run('a','owner','appointments',JSON.stringify({...s.appointments[0],id:'a',patientId:'p',date:'2026-10-10',time:'12:00'}),'now');const previous=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('Timeout')};try{const env={RESEND_API_KEY:'fake',MAIL_FROM:'sender@example.org'};assert.equal((await runDueReminders(db,env,new Date('2026-10-09T12:00:00Z'))).failed,1);await runDueReminders(db,env,new Date('2026-10-09T12:01:00Z'));assert.equal(calls,1);}finally{globalThis.fetch=previous;sqlite.close();}});
test('file deletion outbox retries failures and respects the owner',async()=>{const {sqlite,db}=setup();sqlite.exec("INSERT INTO file_deletions VALUES('owner/a','owner'),('other/b','other')");const failed={delete:async()=>{throw new Error('unavailable')}} as unknown as R2Bucket;await cleanDeletedFiles(db,failed,'owner');assert.equal((sqlite.prepare('SELECT count(*) AS n FROM file_deletions').get() as any).n,2);const removed:string[]=[];await cleanDeletedFiles(db,{delete:async(key:string)=>{removed.push(key)}} as unknown as R2Bucket,'owner');assert.deepEqual(removed,['owner/a']);assert.equal((sqlite.prepare('SELECT count(*) AS n FROM file_deletions').get() as any).n,1);sqlite.close();});
