export type Patient={id:string;firstName:string;lastName:string;birthDate:string;sex:string;birthPlace:string;birthCode:string;cf:string;email:string;phone:string;address:string;city:string;zip:string;pathway:string;notes:string;whatsapp:boolean;emailConsent:boolean;privacy:boolean;opposition:boolean;createdAt:string};
export type Appointment={id:string;patientId:string;date:string;time:string;duration:number;type:string;status:string;mode:string;note:string;reminderHours:number};
export type DocumentRecord={id:string;patientId:string;name:string;kind:string;size:number;date:string;key:string;direction:string};
export type Invoice={id:string;patientId:string;number:string;date:string;paidDate:string;description:string;amount:number;stamp:number;payment:string;status:string;tsStatus:string;opposition:boolean};
export type Message={id:string;patientId:string;appointmentId?:string;channel:string;body:string;status:string;date:string;providerId?:string};
export type Settings={name:string;qualification:string;vat:string;address:string;email:string;phone:string;reminderHours:number;invoicePrefix:string;invoiceNext:number;tsType:string};
export type Studio={patients:Patient[];appointments:Appointment[];documents:DocumentRecord[];invoices:Invoice[];messages:Message[];settings:Settings};
export const defaultSettings:Settings={name:'Clarissa Bandini',qualification:'Nutrizionista · Laureata in Psicologia',vat:'',address:'',email:'',phone:'',reminderHours:24,invoicePrefix:'',invoiceNext:1,tsType:''};
export const emptyStudio=():Studio=>({patients:[],appointments:[],documents:[],invoices:[],messages:[],settings:{...defaultSettings}});
const odd=[1,0,5,7,9,13,15,17,19,21];
const oddLetters=[1,0,5,7,9,13,15,17,19,21,2,4,18,20,11,3,6,8,12,14,16,10,22,25,24,23];
const omocodia='LMNPQRSTUV';
export function cfChecksum(s:string){let total=0;for(let i=0;i<15;i++){const n=/\d/.test(s[i])?Number(s[i]):s.charCodeAt(i)-65;total+=i%2===0?(/\d/.test(s[i])?odd[n]:oddLetters[n]):n;}return String.fromCharCode(65+total%26);}
export function normalizeCf(s:string){return s.trim().toUpperCase().replace(/\s/g,'');}
export function validateCf(cf:string,birthDate:string,sex?:string,birthCode?:string){const s=normalizeCf(cf);if(!/^[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]$/.test(s))return 'Il codice fiscale deve avere 16 caratteri validi.';if(cfChecksum(s)!==s[15])return 'Il carattere di controllo del codice fiscale non è corretto.';let decoded=s.split('');for(const pos of [6,7,9,10,12,13,14])if(omocodia.includes(decoded[pos]))decoded[pos]=String(omocodia.indexOf(decoded[pos]));const plain=decoded.join('');if(birthDate){const [y,m,d]=birthDate.split('-').map(Number);const dt=new Date(Date.UTC(y,m-1,d));if(!y||dt.getUTCFullYear()!==y||dt.getUTCMonth()!==m-1||dt.getUTCDate()!==d||birthDate>localDate())return 'La data di nascita non è valida.';const day=Number(plain.slice(9,11));if(Number(plain.slice(6,8))!==y%100||plain[8]!=='ABCDEHLMPRST'[m-1]||day%40!==d)return 'Il codice fiscale non corrisponde alla data di nascita.';if(sex&&day!==(d+(sex==='F'?40:0)))return 'Il codice fiscale non corrisponde al sesso anagrafico.';}if(birthCode&&plain.slice(11,15)!==birthCode.toUpperCase())return 'Il codice catastale del luogo di nascita non corrisponde.';return '';}
export function nameCode(name:string,isFirst=false){const s=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z]/g,'');let c=s.replace(/[AEIOU]/g,'');if(isFirst&&c.length>=4)c=c[0]+c[2]+c[3];return (c+s.replace(/[^AEIOU]/g,'')+'XXX').slice(0,3);}
export function validatePatient(p:Patient){if(!p.firstName.trim()||!p.lastName.trim())return 'Inserisci nome e cognome.';if(!p.birthDate)return 'Inserisci la data di nascita.';const dt=new Date(p.birthDate+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(p.birthDate)||isNaN(dt.getTime())||dt.toISOString().slice(0,10)!==p.birthDate||p.birthDate>localDate())return 'Data di nascita non valida.';if(p.cf){const error=validateCf(p.cf,p.birthDate,p.sex,p.birthCode);if(error)return error;const s=normalizeCf(p.cf);if(s.slice(0,3)!==nameCode(p.lastName)||s.slice(3,6)!==nameCode(p.firstName,true))return 'Nome o cognome non corrispondono al codice fiscale. Verifica i dati anagrafici ufficiali.';}if(p.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email))return 'L’indirizzo email non è valido.';if(p.phone&&!/^\+?[\d\s-]{8,20}$/.test(p.phone))return 'Il numero di telefono non è valido.';if(p.zip&&!/^\d{5}$/.test(p.zip))return 'Il CAP deve avere 5 cifre.';return '';}
export function localDate(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);}
export function appointmentError(a:Appointment,all:Appointment[]){if(!/^\d{4}-\d{2}-\d{2}$/.test(a.date)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(a.time)||![20,30,45,60].includes(a.duration))return 'Data, ora o durata non validi.';const parsed=new Date(a.date+'T12:00:00Z');if(isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==a.date)return 'La data dell’appuntamento non è valida.';const start=Number(a.time.slice(0,2))*60+Number(a.time.slice(3));if(start+a.duration>1440)return 'La visita deve terminare nella stessa giornata.';if(a.status!=='Annullato'&&all.some(x=>x.id!==a.id&&x.status!=='Annullato'&&x.date===a.date&&start<Number(x.time.slice(0,2))*60+Number(x.time.slice(3))+x.duration&&start+a.duration>Number(x.time.slice(0,2))*60+Number(x.time.slice(3))))return 'Questo orario si sovrappone a un altro appuntamento.';return '';}
export const currency=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);
export const displayDate=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'long',year:'numeric'});
export function reminderText(a:Appointment){return `Lo studio di Clarissa Bandini ti ricorda l’appuntamento del ${displayDate(a.date)} alle ${a.time}${a.mode==='Online'?' online':''}. Per modifiche contatta lo studio. A presto!`;}
export function validateInvoice(i:Invoice,p:Patient,settings:Settings){if(!settings.vat||!/^\d{11}$/.test(settings.vat)||!settings.address)return 'Completa partita IVA e indirizzo dello studio nelle impostazioni.';if(!p.cf||validateCf(p.cf,p.birthDate,p.sex,p.birthCode))return 'Serve un codice fiscale del paziente valido.';if(!p.address||!p.city||!p.zip)return 'Completa l’indirizzo di fatturazione del paziente.';if(!Number.isFinite(i.amount)||i.amount<=0)return 'L’importo deve essere maggiore di zero.';return '';}
export function tsEligibility(i:Invoice,p:Patient){if(i.status!=='Pagata'||!i.paidDate)return 'Registra prima il pagamento e la data di incasso.';if(!p.cf||validateCf(p.cf,p.birthDate,p.sex,p.birthCode))return 'Codice fiscale non valido.';return '';}
export function isoAppointment(a:Appointment){const utc=new Date(`${a.date}T${a.time}:00Z`);const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Rome',hour:'numeric',hourCycle:'h23',minute:'numeric'}).formatToParts(utc);const h=Number(parts.find(x=>x.type==='hour')!.value);const offset=(h-utc.getUTCHours()+24)%24;return new Date(utc.getTime()-offset*3600000);}
