export type ProviderSecrets={RESEND_API_KEY?:string;MAIL_FROM?:string;WHATSAPP_TOKEN?:string;WHATSAPP_PHONE_ID?:string;WHATSAPP_TEMPLATE?:string;WHATSAPP_LANGUAGE?:string;META_GRAPH_VERSION?:string;RESEND_WEBHOOK_SECRET?:string;META_APP_SECRET?:string;WHATSAPP_VERIFY_TOKEN?:string;REMINDER_JOB_SECRET?:string;REMINDER_AUTOMATION_ENABLED?:string};
export function providerReadiness(s:ProviderSecrets){const missing=(keys:(keyof ProviderSecrets)[])=>keys.filter(k=>!s[k]?.trim());const emailMissing=missing(['RESEND_API_KEY','MAIL_FROM']),whatsappMissing=missing(['WHATSAPP_TOKEN','WHATSAPP_PHONE_ID','WHATSAPP_TEMPLATE','META_GRAPH_VERSION']);return {email:!emailMissing.length,whatsapp:!whatsappMissing.length,emailMissing,whatsappMissing,emailTracking:!!s.RESEND_WEBHOOK_SECRET,whatsappTracking:!!(s.META_APP_SECRET&&s.WHATSAPP_VERIFY_TOKEN),schedulerConfigured:!!(s.REMINDER_JOB_SECRET&&s.REMINDER_AUTOMATION_ENABLED==='true')};}
export function normalizePhone(to:string){const phone=to.replace(/[\s()-]/g,'');if(!/^\+[1-9]\d{7,14}$/.test(phone))throw new Error('Inserisci il cellulare con prefisso internazionale, ad esempio +39.');return phone.slice(1);}
const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function emailHtml(body:string,title='Un piccolo promemoria'){return `<div style="background:#f4f5ef;padding:32px;font-family:Arial,sans-serif;color:#293f35"><div style="max-width:560px;margin:auto;background:white;border-radius:16px;padding:32px"><p style="color:#52705b;font-size:12px;letter-spacing:2px">CLARISSA BANDINI · STUDIO</p><h1 style="font-size:24px">${escapeHtml(title)}</h1><p style="line-height:1.8">${escapeHtml(body)}</p><hr style="border:0;border-top:1px solid #e3e8df"><p style="font-size:12px;color:#657167">Nutrizione e ascolto · Per modifiche contatta lo studio.</p></div></div>`;}
export async function sendReminder(channel:string,to:string,body:string,date:string,time:string,secrets:ProviderSecrets,idempotencyKey?:string){
 if(channel==='Email'){
  if(!providerReadiness(secrets).email)throw new Error('Configura il servizio email e il mittente verificato.');
  const response=await fetch('https://api.resend.com/emails',{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+secrets.RESEND_API_KEY,'Content-Type':'application/json',...(idempotencyKey?{'Idempotency-Key':idempotencyKey}:{})},body:JSON.stringify({from:secrets.MAIL_FROM,to:[to],subject:'Promemoria appuntamento · Studio Bandini',text:body,html:emailHtml(body)})});
  if(!response.ok)throw new Error('Il servizio email non ha accettato il messaggio.');const result=await response.json() as {id?:string};if(!result.id)throw new Error('Risposta email senza identificativo.');return result.id;
 }
 if(channel!=='WhatsApp')throw new Error('Canale non valido.');
 if(!providerReadiness(secrets).whatsapp)throw new Error('Configura WhatsApp Business e il template approvato.');
 if(!/^v\d+\.\d+$/.test(secrets.META_GRAPH_VERSION!)||!/^\d+$/.test(secrets.WHATSAPP_PHONE_ID!))throw new Error('Versione Graph API o Phone Number ID non validi.');
 const response=await fetch(`https://graph.facebook.com/${secrets.META_GRAPH_VERSION}/${secrets.WHATSAPP_PHONE_ID}/messages`,{method:'POST',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+secrets.WHATSAPP_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:normalizePhone(to),type:'template',template:{name:secrets.WHATSAPP_TEMPLATE,language:{code:secrets.WHATSAPP_LANGUAGE||'it'},components:[{type:'body',parameters:[{type:'text',text:date},{type:'text',text:time}]}]}})});
 if(!response.ok)throw new Error('WhatsApp non ha accettato il messaggio.');const result=await response.json() as {messages?:{id:string}[]};if(!result.messages?.[0]?.id)throw new Error('Risposta WhatsApp senza identificativo.');return result.messages[0].id;
}
